version: '3.8'

services:
  backend:
    build:
      context: ./backend/tasks
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/${POSTGRES_DB}"
      SPRING_DATASOURCE_USERNAME: "${POSTGRES_USER}"
      SPRING_DATASOURCE_PASSWORD: "${POSTGRES_PASSWORD}"

  frontend:
    build:
      context: ./frontend/task-manager
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/task-manager:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
